### ISSUE TITLE
Extra steps before 'npm run deploy' worked

### ISSUE THREAD

**Issue by knoxilla** [aws-samples/aws-serverless-ai-stories#2]
Cool project - thanks!

I did get it to deploy, but had to take some extra steps to get it to succeed.  If I didn't do these steps `npm run deploy` would bomb out.  

-  cd backend/src/create-story && npm i
- cd backend/src/generate-audio-for-story && npm i
-  cd backend/src/generate-images-for-story && npm i
-  cd frontend && touch .env

I pass this along in case it makes sense to you!

**Comment by diogozedan** [comment]
Thanks, this really helped!

**Comment by boyney123** [comment]
Thank you @knoxilla I will change the install script to do this too

**Comment by boyney123** [comment]
Closing as script has now been updated, thank you!
